#--------------------------------------------------------------#
#                       Renewable config                       #
#--------------------------------------------------------------#

# Supported: 12, 13, 14, 15, 16, latest
minecraft-version: latest

# Whether to 'punish' players for an unrenewable process
# Example: craft diamonds into a hoe; mine diamond ore
punish-for-irreversible-process: true

# TODO: This feature is not fully tested, please report bugs!
prevent-irreversible-process: false

# Ignore it when creative-mode players destroy an unrenewable
creative-mode-ignore: true

# Alternatively, when a player builds using unrenewables while
# in creative, take the supplies from a storage depot location
creative-unrenewable-sourcing: false
creative-supply-at: CherrySpawn,100,100,100

# If true, items & blocks are rescued immediately before death
# and teleported to this specified location
rescue-items: true
store-items-at: CherrySpawn,100,100,100

# Maximum fortune level available on the server
# Needed to determine how many diamonds ~= 1 diamond ore
max-fortune-level: 3

# If some form of spawner mining with silk touch is enabled,
# Then set this to true to let people mine spawners
silktouch-spawners: false
silktouch-level: 1

#command(s) to run when a player destroys an unrenewable item
punish-command: |
    minecraft:tellraw EvDoc {"text":"%name% destroyed a %type%","color":"gray"}
    scoreboard players add %name% pstats-unrenewables_destroyed 1
    scoreboard players add %type% istats-all_unrenewables 1
#   title %name% times 0 40 20
#   title %name% subtitle ["",{"text":"Destroyed finite resource: ","color":"gray"},{"text":"%type%","color":"yellow"}]
#   title %name% title {"text":""}

# Breaks down unrenewables into their most basic components
# For example: a diamond hoe standardized into 2 diamonds
standardize-rescued-items: true
standardize-if-has-lore: false
standardize-if-has-flags: false
standardize-if-has-name: true
standardize-if-has-enchants: true
standardize-if-has-other-meta: true

# If set to true, all mob drops are considered renewable
# Examples: Shulker_Shell, Totem_of_Undying
renewable-mob-drops: false

# If set to true, any blocks affected by gravity are considered renewable
renewable-gravity-blocks: false

# If true, items with one or more treasure enchantments but zero anvil cost
# are considered renewable
renewable-rc0: false

# If true, unobtainable items are considered renewable
renewable-unobtainables: false

# If `renewable-unobtainables` is true:
# Setting to true will treat as unrenewable (otherwise treated as renewable)
# If `renewable-unobtainables` is false:
# Setting to true will treat as renewable (otherwise treated as unrenewable)
obtainable:
  spawners: false
  spawn-eggs: false
  infested-blocks: false
  command-blocks: false
  bedrock: false
  end-portals: false
  barriers-obtainable: false
  structure-blocks: false
  light-blocks: false
  petrified-slabs: false
  reinforced-deepslate: false
  player-heads: true
  illegal-enchantments: true  #VoteToken needs this for the glint effect
  conflicting-enchantments: false
  oversized-enchantments: false

# Here you can specify any renewable items you want
# 'rescue-items' to treat as if they were unrenewable
rescued-renewables: {WRITTEN_BOOK, WRITABLE_BOOK}

# If there is an item that is usually unrenewable, but on your server
# it can be farmed infinitely renewably, add it here
artificial-renewables: {}

# Punish players for destroying rescued-renewables
punish-rescued-renewables: false