name: Renewable
main: net.evmodder.Renewable.Renewable
author: EvModder
website: https://dev.bukkit.org/projects/renewable
description: Detect unrenewable item loss.
#2=update to MC 1.20, remove old code for things which are now renewable
#1=
version: 2.0
api-version: 1.13

commands:
   renewable:
      description: Test if the item you are holding is renewable
      usage: /renewable
      aliases: [renew,isrenew,isrenewable,unrenewable,isunrenewable]
      permission: renewable.check
      permission-message: You do not have permission to do this.

permissions:
   renewable.check:
      description: Permission to use /renewable
      default: op