name: Renewable
main: net.evmodder.Renewable.Renewable
author: EvModder/EvDoc/Evil_Witchdoctor
version: 1.7 #7=CrSupply
api-version: 1.13

commands:
   renewable:
      description: Test if the item you are holding is renewable
      usage: /renewable
      aliases: [renew,isrenew,isrenewable,unrenewable,isunrenewable]
      permission: renewable.check
      permission-message: You do not have permission to do this.

permissions:
   renewable.check:
      description: Permission to use /renewable
      default: op